allowBuilds:
  '@logicflow/core': true
  '@parcel/watcher': true
  '@vue-office/docx': true
  '@vue-office/excel': true
  '@vue-office/pdf': true
  es5-ext: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@antfu/eslint-config@9.3.0'
shellEmulator: true

trustPolicy: off

packages:
  - 'packages/*'
  - 'docs'
