/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EasyButton: typeof import('@raopan/easy-ui')['EasyButton']
    EasyForm: typeof import('@raopan/easy-ui')['EasyForm']
    EasyFormItem: typeof import('@raopan/easy-ui')['EasyFormItem']
    EasyInput: typeof import('@raopan/easy-ui')['EasyInput']
    EasyMarkdown: typeof import('@raopan/easy-ui/markdown')['EasyMarkdown']
    EasyModal: typeof import('@raopan/easy-ui')['EasyModal']
    EasySearchForm: typeof import('@raopan/easy-ui')['EasySearchForm']
    EasySelect: typeof import('@raopan/easy-ui')['EasySelect']
    EasyTable: typeof import('@raopan/easy-ui')['EasyTable']
    EasyTag: typeof import('@raopan/easy-ui')['EasyTag']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const EasyButton: typeof import('@raopan/easy-ui')['EasyButton']
  const EasyForm: typeof import('@raopan/easy-ui')['EasyForm']
  const EasyFormItem: typeof import('@raopan/easy-ui')['EasyFormItem']
  const EasyInput: typeof import('@raopan/easy-ui')['EasyInput']
  const EasyMarkdown: typeof import('@raopan/easy-ui/markdown')['EasyMarkdown']
  const EasyModal: typeof import('@raopan/easy-ui')['EasyModal']
  const EasySearchForm: typeof import('@raopan/easy-ui')['EasySearchForm']
  const EasySelect: typeof import('@raopan/easy-ui')['EasySelect']
  const EasyTable: typeof import('@raopan/easy-ui')['EasyTable']
  const EasyTag: typeof import('@raopan/easy-ui')['EasyTag']
  const ElBacktop: typeof import('element-plus/es')['ElBacktop']
  const ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
  const ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
  const ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElText: typeof import('element-plus/es')['ElText']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}